import { readable, writable } from "svelte/store";

export const settings = writable({
  size: 50,
  rotateX: -20,
  rotateY: -40,
});

export const tiles = readable([
  { color: "#C41E3A", slug: "front", rotateX: 0, rotateY: 0 },
  { color: "#FF5800", slug: "right", rotateX: 0, rotateY: 90 },
  { color: "#0051BA", slug: "back", rotateX: 0, rotateY: 180 },
  { color: "#DDDDDD", slug: "left", rotateX: 0, rotateY: -90 },
  { color: "#009E60", slug: "top", rotateX: 90, rotateY: 0 },
  { color: "#FFD500", slug: "bottom", rotateX: -90, rotateY: 0 },
]);

export const pieces = writable([
  {
    id: 1,
    translateX: 0,
    translateY: 0,
    translateZ: 0,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 2,
    translateX: 0,
    translateY: 1,
    translateZ: 0,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 3,
    translateX: 0,
    translateY: 2,
    translateZ: 0,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 4,
    translateX: 1,
    translateY: 0,
    translateZ: 0,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 5,
    translateX: 1,
    translateY: 1,
    translateZ: 0,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 6,
    translateX: 1,
    translateY: 2,
    translateZ: 0,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 7,
    translateX: 2,
    translateY: 0,
    translateZ: 0,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 8,
    translateX: 2,
    translateY: 1,
    translateZ: 0,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 9,
    translateX: 2,
    translateY: 2,
    translateZ: 0,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 10,
    translateX: 0,
    translateY: 0,
    translateZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 11,
    translateX: 0,
    translateY: 1,
    translateZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 12,
    translateX: 0,
    translateY: 2,
    translateZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 13,
    translateX: 1,
    translateY: 0,
    translateZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 14,
    translateX: 1,
    translateY: 1,
    translateZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 15,
    translateX: 1,
    translateY: 2,
    translateZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 16,
    translateX: 2,
    translateY: 0,
    translateZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 17,
    translateX: 2,
    translateY: 1,
    translateZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 18,
    translateX: 2,
    translateY: 2,
    translateZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 19,
    translateX: 0,
    translateY: 0,
    translateZ: 2,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 20,
    translateX: 0,
    translateY: 1,
    translateZ: 2,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 21,
    translateX: 0,
    translateY: 2,
    translateZ: 2,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 22,
    translateX: 1,
    translateY: 0,
    translateZ: 2,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 23,
    translateX: 1,
    translateY: 1,
    translateZ: 2,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 24,
    translateX: 1,
    translateY: 2,
    translateZ: 2,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 25,
    translateX: 2,
    translateY: 0,
    translateZ: 2,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 26,
    translateX: 2,
    translateY: 1,
    translateZ: 2,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  {
    id: 27,
    translateX: 2,
    translateY: 2,
    translateZ: 2,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
]);
